<title><?php echo $this->pageTile ="Download Image File"?></title>
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<div id="z_layout_box_main" align="center"></div>
    <div style="color: red;">
	<?php echo $this->dumpFlashMessages(); ?>
	</div>
	<div id="contents" class="info text03m">
        <div class="infocontents">
           <form action="/download/list" method="post" id="submitForm" name="submitForm" enctype="multipart/form-data">
           <div class="infotableset">
				   <div>
				   </div>
				
					<div class="pager">
					<p>
					<a href="/upload/request">Add Image</a>
					
					</p>
			        <?php echo $this->paginator; ?>
					</div>
                  <table border="0" cellpadding="0" cellspacing="0" class="infotable02" id="tablecontent">
                         <tbody>
                               <tr>
                                    <th class="thleft"><?php echo $this->formCheckbox('cbx');?></th>
                                    <th class="thcenter">File name</th>    
                               </tr>
                               <tr>
                                    
							      <?php foreach ($this->paginator as $item): ?>
							      <td style = "text-align: center"><span class="cb"><?php echo $this->formCheckbox('cbox',$item->id, array('name' => 'cbox', 'id' =>'cbox'.$item->id, 'class'=>'cbo'));?></span>	
								   </td>	
							      <td style="text-align: center">
									   <a href="/download/download?id=<?php echo $this->escape($item->id) ?>">
										<?php echo StringUtil::getViewSubString($this->escape($item->path),$this->max_display_char); ?> 
										
										</a>
								
								   </td>
								   
								  	
                               </tr>
                               
                                <?php endforeach; ?>
                         </tbody>
                  </table>
                  <table>
                         <tr>
                             
                                 <td align ="center"><?php echo $this->formButton('btn','Delete', array('class'=>'zbtn_short', 'onclick'=>'onDelete();'));?></td>
                                     
                         </tr>
                 </table>
                 
                   <!--padding-->
                 <div class="pager">
					<?php echo $this->paginator; ?>
				</div>
					<!-- end padding -->
				</div>
           </form>
           </div>
  </div>
  
 <form id = "deleteForm" name = "deleteForm" 
action = "/download/delete" method = "post">
      
</form>
  
  <script type = "text/javascript">

		$("#cbx").click(function(){
		    $('input:checkbox').not(this).prop('checked', this.checked);
		});


  function onDelete() {
	  $('#deleteForm').empty();
		$('input:checkbox[name=cbox]:checked').each(function()
				{
			       $('#deleteForm').append('<input type="hidden" name="id[]" value="'+$(this).val()+'" />');
				});
			$('#deleteForm').submit();
  }


  </script>
  