<title><?php echo $this->pageTitle = 'Staff Management'?></title>
<div id ="contents" class = "ifoud text03m">
    <div class="infoudcontents">
      <h2>Edit Staff</h2>
      <div class="infoudtable">
           <form action = "/staff/confirm-edit" method = "post" id = "submitForm" name = "submitForm">
                  <?php //echo $this->formHidden('hid', $this->staff_id, array('id'=>'hid', 'name' =>'hid'));?>
                   <table border = "0" cellpadding = "0" cellspacing = "0">
                          <tbody>
                                 
                                 <tr>
                                     <th class = "infoudtablebb">Name</th>
                                     <td class = "infoudtablebb">
                                         <?php echo $this->formText('name', $this->request->name, array('class'=> 'w300', 'style' =>'margin-left: 20px'));?>
                                         <br>
                                         <div style ="color:red; text-align: left;">
                                         <?php echo $this->formError('name');?>
                                         </div>
                                      </td>
                                 </tr>
                                 <tr>
                                     <th class = "infoudtablebb">Department</th>
                                     <td class = "infoudtablebb">
                                         <?php 
                                                  echo $this->formSelect('option', null, array('name'=>'option', 'id'=>'option', 'onchange'=>'AjaxFunction();'), $this->option);
                                                  
                                          ?>
                                         <br>
                                         <div style ="color:red; text-align: left;">
                                         <?php echo $this->formError('option');?>
                                         </div>
                                      </td>
                                 </tr>
                                 
                                 <tr>
                                     <th class = "infoudtablebb">Position</th>
                                     <td class = "infoudtablebb">
                                         <?php 
                                                  echo $this->formSelect('sbt_pos', null, array('name'=>'sbt_pos', 'id'=>'sbt_pos'));
                                                  
                                          ?>
                                         <br>
                                         <div style ="color:red; text-align: left;">
                                         <?php echo $this->formError('sbt_pos');?>
                                         </div>
                                      </td>
                                 </tr>
                                  
                                 
                                 
                                 <tr>
                                     <th class = "infoudtablebb">Email</th>
                                     <td class = "infoudtablebb">
                                         <?php echo $this->formText('email', $this->request->email, array('class'=> 'w300', 'style' =>'margin-left: 20px'));?>
                                         <br>
                                         <div style ="color:red; text-align: left;">
                                         <?php echo $this->formError('email');?>
                                         </div>
                                      </td>
                                 </tr>
                                
                          </tbody>
                   </table>
                   <table class ="ztable_horizontal" style = "padding-left:18% !important">
                         <tr>
                              <td><?php echo $this->formButton('btSave', 'Save', array('class' => 'zbtn_short','onclick'=> 'onSubmit();')); ?>
						      </td>
						      <td><?php echo $this->formButtonTo(null, 'Back', '/staff/list', array('class' => 'zbtn_back')); ?>
						      </td>
                         </tr>
                   </table>
                   <?php echo $this->formHidden('token', $this->token);?>
                   <?php echo $this->formHidden('staff_id', $this->request->staff_id);?>
                  </form>
		</div>
	</div>
</div>


<div class="modal" id="yesno" title="Alert"><p>Do you want edit information ?</p></div>

<script type="text/javascript">
function AjaxFunction()
{
     var httpxml;

    // Firefox, Opera 8.0+, Safari
    httpxml=new XMLHttpRequest();
  
function stateck() 
{
    if(httpxml.readyState==4)
      {
//          alert(httpxml.responseText);
         var myarray = JSON.parse(httpxml.responseText);
//          var myarray=myarray.split(",");
         for(j=document.submitForm.sbt_pos.options.length;j>0;j--)
          {
              document.submitForm.sbt_pos.remove(j-1);
          }

//       $.each(myarray, function(key, value) {
//           alert(key + ' ' + value);
//       });



//          for (i=0;i<myarray.length;i++)
         for(var key in myarray)
         {
             var optn = document.createElement("OPTION");
             optn.text = myarray[key];
//              optn.value = myarray[i];
             optn.value = key;
             document.submitForm.sbt_pos.options.add(optn);

         } 
      }
    }
   var url="/staff/position";
	
   var department_id=document.getElementById('option').value;
   url=url+"?dep_id="+department_id;
   url=url+"&sid="+Math.random();
   httpxml.onreadystatechange=stateck;
   //alert(url);
   httpxml.open("GET",url,true);
   httpxml.send(null);
}
                                          
  function onClickSubmit()
  {
	  var submitForm = document.getElementID('submitForm');
	  submitForm.action = '/staff/confirm-edit';
	  submitForm.target = '_seft';
	  submitForm.submit();
  } 

  $(document).ready(function(){
	    var triggers = $(".modalInput").overlay({
	        mask: {
	            color: '#000',
	            loadSpeed: 200,
	            opacity: 0.5
	        },
	        closeOnClick: false
	    });
	    var buttons = $("#yesno button").click(function(e) {
	        var yes = buttons.index(this) === 0;
	        if (yes==true) {
	            $("#deleteForm").submit();
	        }
	    });
	   
	});


	function onSubmit() {
	    $("#yesno" ).dialog({
	     resizable: false,
	     height:140,
	     modal: true,
	     buttons: {
	         "Save": function() {
  	        var submitForm = document.getElementById('submitForm');
  	        submitForm.action ='/staff/confirm-edit';
  	        submitForm.target ='_self';
	           $("#submitForm").submit();
	         },
	         "Cancel": function() {
	             $( this ).dialog( "close" );
	         }
	     }
	 });
	}
	                                 

</script>
