<title><?php echo $this->pageTitle = 'Staff Management'?></title>
<div id ="contents" class = "ifoud text03m">
      <h2>Add Staff</h2>
      <div class ="infoudtable">
           <form action = "/staff/join" method = "post" id = "submitForm" name = "submitForm">
                   <table border = "0" cellpadding = "0" cellspacing = "0">
                          <tbody>
                                 <tr>
                                     <th class = "infoudtablebb">Name</th>
                                     <td class = "infoudtablebb">
                                         <?php echo $this->formText('name', $this->request->name, array('class'=> 'w300', 'style' =>'margin-left: 20px'));?>
                                         <br>
                                         <div style ="color:red; text-align: left;">
                                         <?php echo $this->formError('name');?>
                                         </div>
                                      </td>
                                 </tr>
                                 
                                 <tr>
                                     <th class = "infoudtablebb">Position</th>
                                     <td class = "infoudtablebb">
                                         <?php 
                                                  echo $this->formSelect('sbt_pos', null, array('name'=>'sbt_pos', 'id'=>'sbt_pos'), array('leader' =>'Leader','tester' =>'Tester', 'dev' =>'Dev', 'bse' =>'BSE' ));
                                                  
                                          ?>
                                         <br>
                                         <div style ="color:red; text-align: left;">
                                         <?php echo $this->formError('sbt_pos');?>
                                         </div>
                                      </td>
                                 </tr>
                                 <tr>
                                     <th class = "infoudtablebb">Department</th>
                                     <td class = "infoudtablebb">
                                         <?php 
                                                  echo $this->formSelect('department', null, array('name'=>'department', 'id'=>'department'), array('1' =>'HC','2' =>'KT', '3' =>'NS', '4' =>'CSKH' ));
                                                  
                                          ?>
                                         <br>
                                         <div style ="color:red; text-align: left;">
                                         <?php echo $this->formError('sbt_pos');?>
                                         </div>
                                      </td>
                                 </tr>
                                 
                                 <tr>
                                     <th class = "infoudtablebb">Email</th>
                                     <td class = "infoudtablebb">
                                         <?php echo $this->formText('email', $this->request->email, array('class'=> 'w300', 'style' =>'margin-left: 20px'));?>
                                         <br>
                                         <div style ="color:red; text-align: left;">
                                         <?php echo $this->formError('email');?>
                                         </div>
                                      </td>
                                 </tr>
                                
                          </tbody>
                   </table>
                   <table class ="ztable_horizontal" style = "padding-left:18% !important">
                         <tr>
                              <td><?php echo $this->formButton('btSave', 'Add', array('class' => 'zbtn_short','onclick'=> 'onSubmit();')); ?>
						      </td>
						      <td><?php echo $this->formButtonTo(null, 'Exit', '/staff/list', array('class' => 'zbtn_back')); ?>
						      </td>
                         </tr>
                   </table>
                   <?php echo $this->formHidden('token', $this->token);?>
                   <!-- yes/no dialog -->
        <div class="modal" id="yesno" title="確認">
            <p>Do you accept to add a staff？</p>
        </div>
                  
           </form>
      </div>
</div>
<script type="text/javascript">
// 	function onClickPreview() {
// 		var submitForm = document.getElementById('submitForm');
// 		submitForm.action ='/admin-information/addpreview';
// 		submitForm.target ='_blank';
// 		submitForm.submit();
// 	}

// 	function onClickSubmit(){
// 		var submitForm = document.getElementById('submitForm');
// 		submitForm.action ='/staff/confirm-add';
// 		//submitForm.target ='_self';
// 		submitForm.submit();
// 	}


// 	$(document).ready(function(){
// 	    var triggers = $(".modalInput").overlay({
// 	        mask: {
// 	            color: '#000',
// 	            loadSpeed: 200,
// 	            opacity: 0.5
// 	        },
// 	        closeOnClick: false
// 	    });
// 	    var buttons = $("#yesno button").click(function(e) {
// 	        var yes = buttons.index(this) === 0;
// 	        if (yes==true) {
// 	            $("#deleteForm").submit();
// 	        }
// 	    });
	   
// 	});

// 	$("#submitForm").submit(function(){
// 		var url = '/staff/test';
// 		var data = $("#submitForm").serialize(); 
// 		$.post(url, data, function(success){
// 			alert("OK");
// 		}, 'json');
// 	});

	$("#ajaxBtn").click(function(){
		var url = '/staff/test';
		var data = 'data=1'; 
		$.post(url, data, function(success){
			alert(success.ok);
		});
	});

	function onSubmit() {
// 		var url = '/staff/test';
// 		var data = $("#submitForm").serialize(); 
// 		$.post(url, data, function(success){
// 			alert("OK");
// 		}, 'json');
	    $("#yesno" ).dialog({
	     resizable: false,
	     height:140,
	     modal: true,
	     buttons: {
	         "Accept": function() {
    	        var submitForm = document.getElementById('submitForm');
    	        submitForm.action ='/staff/join';
    	        
    	        submitForm.target ='_self';
	           $("#submitForm").submit();
	         },
	         "Ignore": function() {
	             $( this ).dialog( "close" );
	         }
	     }
	 });
	}

	function onClick(){
		$(document).ready(function(){
			$("#chck").click(function(){
				$.ajax({
					type: "POST",
					url:" ",
					data: "",
				
				});
			});
		});
	}
	
</script>

