<title>List One</title>
<div id="contents" class="info text03m"> 
   <div class="infocontents">
          <form action="/staff/list_v1" method="post">
       <div class="infotableset">
          <div class="pager">
              <?php echo $this->paginator;?>
          </div>
         <table class="infotable02" id="tablecontent">
               <tbody>
                     <tr>
                          <th>Name</th>
                          <th>Email</th>
                          <th>Department</th>
                     </tr>
                     
                     <?php foreach ($this->paginator as $item):?>
                     <tr>
                          <td><?php echo StringUtil::getViewSubString($this->escape($item->name), $this->max_display_char);?></td>
                          <td><?php echo StringUtil::getViewSubString($this->escape($item->email), $this->max_display_char);?></td>
                          <td><?php echo StringUtil::getViewSubString($this->escape($item->department_name), $this->max_display_char);?></td>
                     </tr>
                     <?php endforeach;?>
               </tbody>
         </table>
         <div class="pager">
	         <?php echo $this->paginator; ?>
		 </div>
        </div>
    </form>
   </div>
     
</div>

