
<title><?php echo $this->pageTitle = 'ログイン ｜ 該非判定WEBシステム ｜ 株式会社ディスコ'; //?>
</title>
<?php $this->isNotHeader = true; ?>

<div id="z_layout_box_main" align="center">
<?php echo $this->dumpFlashMessages(); ?>
	<div id="top_left_container">
		<div id="header">
			<h1>
				<a href="http://www.disco.co.jp"><img
					src="/resources/image/logo.jpg" alt="DISCO" width="205" height="48"
					border="0"> </a>
			</h1>
		</div>

		<div id="gnavi02"></div>

		<h2 class="pb10">
			<img src="/resources/image/service_ttl.gif" width="716" height="46"
				alt="該非判定書発行サービス">
		</h2>

		<form action="/customer/confirm-login" method="post" id="registerForm">
			<div style="color: red;">
			<?php echo $this->formError('login'); ?>
			</div>
			<div id="contents" class="login morefooterspace text03m">
				<div class="inputbox">
					<ul>
						<li class="inputtxt">E-mail</li>
						<li><?php echo $this->formText('mailAdress', $this->mailAdress, array('class' => 'w300', 'style' => 'ime-mode: disabled;'));?>
							<?php if (NULL !== $this->formError('mailAdress')):?>
    							<div style="color: red; text-align: left">&nbsp;
    							    <?php echo $this->formError('mailAdress'); ?>
    							</div>
							<?php endif;?>
						</li>
					</ul>
					<ul>
						<li class="inputtxt">Password</li>
						<li><?php echo $this->formPassword('password', $this->escape($this->password), array('class' => 'form-control'));?>

							<div style="color: red; text-align: left">&nbsp;
							<?php echo $this->formError('password'); ?>
							</div>
						</li>
					</ul>
					
					<ul>
						<li>
						<?php if (NULL !== $this->mailAdress):?>
						<?php echo $this->formCheckbox('remember', 1, array(), array(1,0));?>
						<?php else:?>
						<?php echo $this->formCheckbox('remember', 0, array(), array(1,0));?>
						<?php endif;?>
							&nbsp;Do you want to remember?</li>
						<li></li>
					</ul>
					<p align="center">
					<?php echo $this->formSubmit(null, 'Login', array('class' => 'zbtn_short')); ?>
					</p>
				</div>
				<p class="pw_forgets left_arrow">
					<img src="/resources/image/icon_arrow01.gif" width="8" height="8"
						alt="">Forget password? 
						<?php echo "<a href='/resume/request'>Click here</a>";?>
				</p>
			</div>
		</form>
	</div>
	<!-- #top_left_container -->
</div>
<!-- #z_layout_box_main -->



